### PR TITLE
Updating Ergo Docs Page Readme/ some pages to remove error 404 links. Small Fix

### PR DESCRIPTION
**Pull request by CChristian1931**
Hi, I edited the mark down for the read me to change the link to reflect the actual link so that people don't encounter the error 502 as per  issue #6. 

- I also updated the links that were throwing error 404 in order to reflect the proper links. 

That is all for my small patch to the ergo github doc page. I will make more updates if I notice anything else or feel there should be more information to add.  If there is any questions you may have feel free to reply.

### CODE REVIEW

**Comment by glasgowm148** [comment]
Thanks for your contributions! Could you fix the conflicts?

**Comment by CChristian1931** [comment]
> Thanks for your contributions! Could you fix the conflicts? 

Hey Glasgow, no worries I will take a look at this today. And fix up the conflicts.

**Comment by CChristian1931** [comment]
> > Thanks for your contributions! Could you fix the conflicts?
> 
> Hey Glasgow, no worries I will take a look at this today. And fix up the conflicts.

Hi again, the conflicts should be fixed now. If there are any more issues feel free to reach out to me. Thank you.

**Comment by glasgowm148** [comment]
Thanks!

**Pull request merged**
